# Generated by Django 6.1.1 on 2026-10-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_availability_application_cgpa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='application',
            name='match_percentage',
            field=models.IntegerField(default=0, help_text='Skill match percentage'),
        ),
        migrations.AddField(
            model_name='application',
            name='matched_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='missing_skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
