# Generated by Django 6.1.1 on 2026-09-06 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('job_type', models.CharField(default='Full-Time', max_length=100)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('minimum_cgpa', models.FloatField(default=0.0)),
                ('maximum_backlogs', models.IntegerField(default=0)),
                ('graduation_year', models.IntegerField()),
                ('application_deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
                ('required_skills', models.ManyToManyField(to='students.skill')),
            ],
        ),
    ]
