# Generated by Django 6.1.1 on 2026-09-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_fields'),
        ('students', '0004_profile_professional_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='eligible_degree',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_required',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='job',
            name='required_frameworks',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='job',
            name='required_programming_languages',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='job',
            name='required_technologies',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='required_skills',
            field=models.ManyToManyField(related_name='required_jobs', to='students.skill'),
        ),
    ]
