# Generated by Django 6.1.1 on 2026-09-10 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_profile_professional_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='current_semester',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='job_type',
            field=models.CharField(blank=True, choices=[('INTERNSHIP', 'Internship'), ('FULL_TIME', 'Full-time'), ('BOTH', 'Internship or full-time')], max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_job_role',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_work_location',
            field=models.CharField(blank=True, choices=[('REMOTE', 'Remote'), ('HYBRID', 'Hybrid'), ('ON_SITE', 'On-site')], max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
