# Generated by Django 6.1.1 on 2026-09-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentprofile_current_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_domain',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
