# Generated by Django 6.1.1 on 2026-09-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_studentprofile_preferred_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='job_type',
            field=models.CharField(blank=True, choices=[('INTERNSHIP', 'Internship'), ('FULL_TIME', 'Full-time'), ('BOTH', 'Internship and full-time')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='preferred_work_location',
            field=models.CharField(blank=True, choices=[('REMOTE', 'Remote'), ('HYBRID', 'Hybrid'), ('ONSITE', 'On-site')], max_length=20),
        ),
    ]
