# Generated by Django 6.1.1 on 2026-09-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='analysis_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
