# Generated by Django 6.1.1 on 2026-09-18 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_resumeanalysis_analysis_data'),
        ('ai_engine', '0002_resumeanalysis_analysis_result_and_more'),
    ]

    operations = [
    ]
