# Generated by Django 6.1.1 on 2026-10-04 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_merge_20260918_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='analysis_data',
        ),
    ]
