# Generated by Django 6.1.1 on 2026-10-07 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0004_remove_resumeanalysis_analysis_data'),
        ('jobs', '0003_job_eligible_degree_job_experience_required_and_more'),
        ('students', '0007_remove_studentprofile_preferred_domain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightSimulationChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('target_role', models.CharField(max_length=150)),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner (Entry-Level / Intern)'), ('INTERMEDIATE', 'Intermediate (1-2 yrs experience)'), ('ADVANCED', 'Advanced (Senior / High Bar)')], default='INTERMEDIATE', max_length=20)),
                ('estimated_minutes', models.PositiveIntegerField(default=30)),
                ('scenario_brief', models.TextField(help_text='Realistic workplace scenario and context.')),
                ('problem_statement', models.TextField(help_text='Specific problem to solve or analyze.')),
                ('dataset_or_context', models.TextField(blank=True, help_text='Sample dataset, code snippet, or operational logs.')),
                ('deliverables_required', models.TextField(help_text='Expected deliverables from candidate.')),
                ('rubric_criteria', models.JSONField(blank=True, default=list)),
                ('skills_tested', models.JSONField(blank=True, default=list)),
                ('badge_name', models.CharField(default='Role-Ready Simulator Badge', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityCompilerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role_title', models.CharField(max_length=200)),
                ('target_company', models.CharField(blank=True, max_length=200)),
                ('job_description_raw', models.TextField(blank=True)),
                ('plain_language_skills', models.JSONField(blank=True, default=list)),
                ('evidence_mapping', models.JSONField(blank=True, default=list)),
                ('readiness_percentage', models.PositiveIntegerField(default=75)),
                ('schedule_type', models.CharField(choices=[('5_DAY_SPRINT', '5-Day Intensive Sprint (~15 hrs/wk)'), ('2_WEEK_SPRINT', '2-Week Balanced Sprint (~8 hrs/wk)'), ('4_WEEK_SPRINT', '4-Week Flexible Sprint (~4 hrs/wk)')], default='2_WEEK_SPRINT', max_length=30)),
                ('available_hours_per_week', models.PositiveIntegerField(default=10)),
                ('sprint_plan', models.JSONField(blank=True, default=list)),
                ('proof_brief_token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compiled_sessions', to='jobs.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compiled_opportunities', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeerContributionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=150)),
                ('reviewer_role', models.CharField(max_length=150)),
                ('project_name', models.CharField(max_length=200)),
                ('review_text', models.TextField()),
                ('skills_endorsed', models.JSONField(blank=True, default=list)),
                ('verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProofPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Role-Ready Candidate Evidence', max_length=255)),
                ('public_share_token', models.CharField(max_length=64, unique=True)),
                ('is_public', models.BooleanField(default=True)),
                ('allowed_employers', models.TextField(blank=True, help_text='Comma-separated employer names or blank for all.')),
                ('include_simulations', models.BooleanField(default=True)),
                ('include_projects', models.BooleanField(default=True)),
                ('include_coursework', models.BooleanField(default=True)),
                ('include_peer_reviews', models.BooleanField(default=True)),
                ('overall_evidence_score', models.PositiveIntegerField(default=85)),
                ('demonstrated_skills_count', models.PositiveIntegerField(default=0)),
                ('inferred_skills_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proof_passport', to='students.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PassportArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('SIMULATION', 'Work Simulation (Career Flight Simulator)'), ('PROJECT', 'Project Artifact'), ('COURSEWORK', 'Coursework & Capstone'), ('PEER_REVIEW', 'Peer / Mentor Contribution'), ('CERTIFICATION', 'Verified Certification')], default='PROJECT', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('source_reference', models.CharField(max_length=255)),
                ('external_url', models.URLField(blank=True)),
                ('confidence_level', models.CharField(choices=[('DEMONSTRATED', 'Demonstrated (Work-backed)'), ('INFERRED', 'Inferred (Profile / Resume claim)')], default='DEMONSTRATED', max_length=20)),
                ('skills_evidenced', models.JSONField(blank=True, default=list)),
                ('score_or_grade', models.CharField(blank=True, max_length=50)),
                ('is_pinned', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='ai_engine.proofpassport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_text', models.TextField(help_text="Candidate's solution, code, or analysis.")),
                ('recommendations', models.TextField(blank=True, help_text='Actionable business/technical recommendations.')),
                ('artifact_url', models.URLField(blank=True, help_text='External link to repo, notebook, or demo.')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('EVALUATED', 'Evaluated')], default='EVALUATED', max_length=20)),
                ('overall_score', models.PositiveIntegerField(default=85)),
                ('execution_score', models.PositiveIntegerField(default=85)),
                ('problem_solving_score', models.PositiveIntegerField(default=85)),
                ('business_impact_score', models.PositiveIntegerField(default=85)),
                ('rigor_score', models.PositiveIntegerField(default=85)),
                ('demonstrated_strengths', models.JSONField(blank=True, default=list)),
                ('skill_gaps', models.JSONField(blank=True, default=list)),
                ('next_practice_mission', models.JSONField(blank=True, default=dict)),
                ('ai_feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ai_engine.flightsimulationchallenge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_submissions', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
