# Generated by Django 6.1.1 on 2026-10-08 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0005_flightsimulationchallenge_opportunitycompilersession_and_more'),
        ('jobs', '0004_job_experience_text_job_is_active_job_qualifications_and_more'),
        ('students', '0007_remove_studentprofile_preferred_domain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeReadinessRadar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(default='CampusLink University Network', max_length=200)),
                ('department', models.CharField(default='All Departments', max_length=100)),
                ('sql_avg', models.PositiveIntegerField(default=38)),
                ('communication_avg', models.PositiveIntegerField(default=52)),
                ('python_avg', models.PositiveIntegerField(default=71)),
                ('excel_bi_avg', models.PositiveIntegerField(default=64)),
                ('problem_solving_avg', models.PositiveIntegerField(default=78)),
                ('total_students_tracked', models.PositiveIntegerField(default=280)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='The 15-minute Role Mission: Junior Data Analyst', max_length=200)),
                ('slug', models.SlugField(default='junior-data-analyst-15m', max_length=200, unique=True)),
                ('target_role', models.CharField(default='Junior Data Analyst', max_length=150)),
                ('estimated_minutes', models.PositiveIntegerField(default=15)),
                ('scenario_brief', models.TextField(default='An e-commerce team sees a 12% drop in repeat purchases. You are tasked with analyzing the drop, inspecting telemetry metrics, and prescribing high-ROI operational interventions.')),
                ('task1_prompt', models.TextField(default='TASK 1. Identify 2 metrics you would inspect.')),
                ('task2_prompt', models.TextField(default='TASK 2. Write one SQL query or explain the logic.')),
                ('task3_prompt', models.TextField(default='TASK 3. Give one business action based on the result.')),
                ('skills_tested', models.JSONField(blank=True, default=list)),
                ('default_next_gap', models.CharField(default='JOINs need practice -> 12-min mission', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeTargetedIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_target', models.CharField(default='SQL', max_length=100)),
                ('target_cohort', models.CharField(default='Bottom 30%', max_length=100)),
                ('targeted_students_count', models.PositiveIntegerField(default=84)),
                ('mission_assigned', models.CharField(default='Targeted SQL Sprint: 15-min Query & Cohort Challenge', max_length=255)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('measured_improvement_pct', models.PositiveIntegerField(default=26)),
                ('launched_at', models.DateTimeField(auto_now_add=True)),
                ('radar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='ai_engine.collegereadinessradar')),
            ],
            options={
                'ordering': ['-launched_at'],
            },
        ),
        migrations.CreateModel(
            name='ProofMinerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_type', models.CharField(choices=[('GITHUB', 'GitHub Repository / Code Link'), ('PROJECT_FILE', 'Project Files / Capstone Artifact'), ('CERTIFICATE', 'Verified Certificate / Credential'), ('MINI_TEST', 'Mini-Test / Timed Mission'), ('MENTOR', 'Peer / Mentor Validation')], default='GITHUB', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('url_or_ref', models.CharField(blank=True, max_length=500)),
                ('skills_connected', models.JSONField(blank=True, default=list)),
                ('evidence_details', models.TextField(blank=True)),
                ('strength', models.CharField(choices=[('Strong', 'Strong'), ('Medium', 'Medium'), ('Inferred', 'Inferred')], default='Strong', max_length=20)),
                ('freshness_label', models.CharField(default='Today', max_length=50)),
                ('is_demonstrated', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_miner_items', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecruiterCandidateProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=150)),
                ('candidate_label', models.CharField(default='Candidate A', max_length=50)),
                ('target_role', models.CharField(default='Data Analyst', max_length=150)),
                ('role_fit_percentage', models.PositiveIntegerField(default=91)),
                ('proof_skills_proven', models.CharField(default='9 / 10', max_length=50)),
                ('why_recommended', models.TextField(default='strong evidence on highest-weight skills.')),
                ('evidence_trail', models.JSONField(blank=True, default=list)),
                ('is_shortlisted', models.BooleanField(default=False)),
                ('mission_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.studentprofile')),
            ],
            options={
                'ordering': ['-role_fit_percentage'],
            },
        ),
        migrations.CreateModel(
            name='RoleDecoderAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(default='Junior Data Analyst', max_length=200)),
                ('company_name', models.CharField(blank=True, default='CampusLink Partner Company', max_length=200)),
                ('job_description_raw', models.TextField()),
                ('extracted_skills', models.JSONField(blank=True, default=list)),
                ('must_have_skills', models.JSONField(blank=True, default=list)),
                ('nice_to_have_skills', models.JSONField(blank=True, default=list)),
                ('experience_signals', models.JSONField(blank=True, default=list)),
                ('normalized_weights', models.JSONField(blank=True, default=dict)),
                ('total_skills_count', models.PositiveIntegerField(default=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decoder_analyses', to='jobs.job')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decoded_roles', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleMissionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task1_answer', models.TextField()),
                ('task2_answer', models.TextField()),
                ('task3_answer', models.TextField()),
                ('logic_score', models.PositiveIntegerField(default=80)),
                ('sql_score', models.PositiveIntegerField(default=75)),
                ('business_thinking_score', models.PositiveIntegerField(default=80)),
                ('overall_score', models.PositiveIntegerField(default=78)),
                ('evidence_captured', models.BooleanField(default=True)),
                ('next_gap', models.CharField(default='JOINs need practice -> 12-min mission', max_length=255)),
                ('ai_evaluation_summary', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ai_engine.rolemission')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_submissions', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
