# Generated by Django 6.1.1 on 2026-10-08 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0006_collegereadinessradar_rolemission_and_more'),
        ('students', '0007_remove_studentprofile_preferred_domain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewArenaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(default='Junior Data Analyst', max_length=150)),
                ('interview_mode', models.CharField(default='Technical & Scenario Deep Dive', max_length=50)),
                ('question_prompt', models.TextField(default='Explain how you would diagnose a 12% drop in repeat purchases using SQL and cohort analysis.')),
                ('candidate_response', models.TextField()),
                ('technical_rigor_score', models.PositiveIntegerField(default=84)),
                ('communication_clarity_score', models.PositiveIntegerField(default=88)),
                ('problem_structuring_score', models.PositiveIntegerField(default=82)),
                ('overall_score', models.PositiveIntegerField(default=85)),
                ('ai_feedback', models.TextField(blank=True)),
                ('key_strengths', models.JSONField(blank=True, default=list)),
                ('improvement_areas', models.JSONField(blank=True, default=list)),
                ('verified_in_passport', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_arena_sessions', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalizedImprovementAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ROLE_MISSION', '15-min Role Mission'), ('PROOF_MINER', 'Proof Miner Upload'), ('INTERVIEW_ARENA', 'AI Interview Arena'), ('PEER_REVIEW', 'Mentor Validation')], default='ROLE_MISSION', max_length=30)),
                ('target_skill', models.CharField(default='SQL', max_length=100)),
                ('expected_roi_boost', models.CharField(default='+9% Role Fit', max_length=50)),
                ('estimated_minutes', models.PositiveIntegerField(default=15)),
                ('action_url', models.CharField(default='/role-mission/', max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('priority_order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvement_actions', to='students.studentprofile')),
            ],
            options={
                'ordering': ['priority_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementRiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('HIGH_RISK', 'High Risk (Immediate Intervention Required)'), ('MODERATE_RISK', 'Moderate Risk (Targeted Gaps)'), ('PLACEMENT_READY', 'Placement Ready (Strong Evidence Base)')], default='MODERATE_RISK', max_length=30)),
                ('risk_score', models.PositiveIntegerField(default=55)),
                ('primary_risk_factors', models.JSONField(blank=True, default=list)),
                ('recommended_intervention', models.CharField(default='Targeted SQL Sprint + 15-min Mission', max_length=255)),
                ('intervention_dispatched', models.BooleanField(default=False)),
                ('proof_coverage_ratio', models.CharField(default='4/9 skills verified', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement_risk_profile', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-risk_score'],
            },
        ),
    ]
