# Generated by Django 6.1.1 on 2026-09-11 20:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('FREE', 'Free'), ('PRO_MONTHLY', 'PRO Monthly'), ('PRO_ANNUAL', 'PRO Annual')], default='FREE', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='created', max_length=15)),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, max_length=255, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255)),
                ('provider', models.CharField(blank=True, default='RAZORPAY', max_length=30)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'status'], name='accounts_pa_user_id_618f05_idx'), models.Index(fields=['plan', 'status'], name='accounts_pa_plan_0c75f8_idx')],
            },
        ),
    ]
