# Generated by Django 6.1.1 on 2026-09-18 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_membership_expiry_date_membership_start_date_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='manual_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='manual_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal admin notes for manual verification.'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_proof',
            field=models.URLField(blank=True, help_text='Optional receipt or proof URL.'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='UPI reference, transaction ID, or payment note.', max_length=255),
        ),
    ]
