# Generated by Django 6.1.1 on 2026-10-08 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_fields'),
        ('students', '0007_remove_studentprofile_preferred_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('Startup', 'High-Growth Startup'), ('Unicorn', 'Tech Unicorn'), ('Enterprise', 'Enterprise / MNC'), ('Product Lab', 'Product & Research Lab')], default='Startup', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='employee_count',
            field=models.CharField(blank=True, default='50-200 members', max_length=80),
        ),
        migrations.AddField(
            model_name='company',
            name='funding_stage',
            field=models.CharField(blank=True, default='Series A / Funded', max_length=80),
        ),
        migrations.AddField(
            model_name='company',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='tech_stack',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Verification Pending'), ('VERIFIED', 'Verified Company'), ('REJECTED', 'Rejected')], default='VERIFIED', max_length=20),
        ),
        migrations.CreateModel(
            name='CompanyConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_role', models.CharField(blank=True, default='', max_length=150)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='CONNECTED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='companies.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_connections', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'company')},
            },
        ),
    ]
