# Generated by Django 6.1.1 on 2026-10-04 04:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockInterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_target', models.CharField(default='Software Engineer Intern', max_length=150)),
                ('company_type', models.CharField(default='Tech Product Startup', max_length=150)),
                ('interview_type', models.CharField(choices=[('HR', 'HR & Culture Fit'), ('TECHNICAL', 'Technical & Problem Solving'), ('BEHAVIORAL', 'Behavioral (STAR Method)'), ('CASE', 'Case Study & Estimation')], default='HR', max_length=50)),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner (Internship / Entry Level)'), ('INTERMEDIATE', 'Intermediate (1-2 yrs experience)'), ('ADVANCED', 'Advanced (Senior / High Bar)')], default='BEGINNER', max_length=30)),
                ('duration_minutes', models.PositiveIntegerField(default=15)),
                ('overall_score', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('communication_score', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('content_score', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('confidence_score', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('body_language_score', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('areas_for_improvement', models.JSONField(blank=True, default=list)),
                ('sample_answer', models.TextField(blank=True)),
                ('practice_plan', models.JSONField(blank=True, default=list)),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('observations', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='COMPLETED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
