import os
import datetime
from django.core.management.base import BaseCommand
from django.utils import timezone
from students.models import Skill
from companies.models import Company
from jobs.models import Job


class Command(BaseCommand):
    help = 'Populates the database with real official top enterprise companies, tech giants, startups, and job openings'

    def handle(self, *args, **kwargs):
        self.stdout.write('Seeding top enterprise companies and verified career opportunities...')

        # Catalog of skills to ensure in database
        skills_master = [
            'Python', 'Java', 'C', 'C++', 'C#', 'JavaScript', 'TypeScript', 'React',
            'Node.js', 'Django', 'Spring Boot', 'SQL', 'MySQL', 'MongoDB', 'PostgreSQL',
            'Redis', 'AWS', 'Azure', 'GCP', 'Docker', 'Kubernetes', 'Machine Learning',
            'Data Science', 'Data Analytics', 'Power BI', 'Tableau', 'DevOps', 'Git',
            'DSA', 'AI', 'System Design', 'REST API', 'Cloud', 'SAP', 'Testing',
            'PyTorch', 'TensorFlow', 'Microservices', 'Kafka', 'Linux', 'Golang',
        ]
        skill_objs = {}
        for s in skills_master:
            obj, _ = Skill.objects.get_or_create(name=s)
            skill_objs[s] = obj

        # Enterprise Catalog
        enterprises = [
            {
                'name': 'Amazon',
                'company_type': 'Enterprise',
                'industry': 'E-Commerce, Cloud Computing & AI',
                'tagline': "Earth's most customer-centric company and world leader in cloud infrastructure",
                'description': 'Amazon guides four principles: customer obsession rather than competitor focus, passion for invention, commitment to operational excellence, and long-term thinking. From AWS to Alexa, our teams engineer solutions at global scale.',
                'website': 'https://www.amazon.jobs',
                'logo_url': '/static/images/company_logos/amazon.svg',
                'headquarters': 'Seattle, Washington, USA',
                'locations': 'Bengaluru, Hyderabad, Chennai, Pune (Hybrid)',
                'tech_stack': 'Java, Python, AWS, SQL, C++, Distributed Systems, DynamoDB',
                'employee_count': '1,500,000+ globally (100,000+ in India)',
                'funding_stage': 'Public (NASDAQ: AMZN)',
                'open_positions': 8,
                'internship_opportunities': 4,
                'jobs': [
                    {
                        'title': 'Software Development Engineer - I (SDE 1)',
                        'job_type': 'Full-Time',
                        'work_mode': 'Hybrid',
                        'location': 'Bengaluru, Karnataka',
                        'salary': '16 - 26 LPA + RSUs',
                        'minimum_cgpa': 7.5,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': '0 - 1 Years / 2025-2026 Batch',
                        'qualifications': 'B.Tech / M.Tech in Computer Science, IT, or related fields. Strong command of Data Structures, Algorithms, and Object-Oriented Design.',
                        'description': 'Build high-scale distributed microservices powering Amazon Retail and Prime. You will architect low-latency APIs, design fault-tolerant database schemas, and deploy containerized services on AWS.',
                        'skills': ['Python', 'Java', 'SQL', 'AWS', 'DSA', 'Machine Learning'],
                        'days_deadline': 45,
                    },
                    {
                        'title': 'Cloud Support Associate - AWS Infrastructure',
                        'job_type': 'Full-Time',
                        'work_mode': 'Onsite',
                        'location': 'Hyderabad, Telangana',
                        'salary': '12 - 18 LPA',
                        'minimum_cgpa': 7.0,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': 'Fresher to 1 Year',
                        'qualifications': 'B.Tech in CS/IT/ECE. Solid networking fundamentals (TCP/IP, DNS), Linux systems, and cloud fundamentals.',
                        'description': 'Diagnose complex cloud architectures, optimize serverless workloads, and assist enterprise customers on Amazon Web Services.',
                        'skills': ['AWS', 'Linux', 'Cloud', 'Python', 'Docker'],
                        'days_deadline': 30,
                    },
                    {
                        'title': 'Software Engineering Intern (Summer 2026)',
                        'job_type': 'Internship',
                        'work_mode': 'Hybrid',
                        'location': 'Bengaluru, Karnataka',
                        'salary': 'Stipend: ₹80,000 / month',
                        'minimum_cgpa': 8.0,
                        'graduation_year': 2026,
                        'experience_required': 0.0,
                        'experience_text': 'Pre-Final / Final Year Students',
                        'qualifications': 'Pursuing B.Tech/B.E in CS/IT with consistent academic performance. Passion for problem-solving.',
                        'description': '3 to 6-month intensive internship working on production systems with dedicated mentorship and full-time PPO conversion opportunity.',
                        'skills': ['Java', 'Python', 'DSA', 'SQL', 'Git'],
                        'days_deadline': 60,
                    }
                ]
            },
            {
                'name': 'Google',
                'company_type': 'Enterprise',
                'industry': 'Search, Cloud, AI & Distributed Systems',
                'tagline': "Organizing the world's information and making it universally accessible and useful",
                'description': 'Google engineers build products that impact billions of people worldwide. In India, engineering centers in Bengaluru and Hyderabad lead core innovations across Google Cloud, Android, YouTube, Payments, and AI research.',
                'website': 'https://careers.google.com',
                'logo_url': '/static/images/company_logos/google.svg',
                'headquarters': 'Mountain View, California, USA',
                'locations': 'Bengaluru & Hyderabad (Hybrid)',
                'tech_stack': 'C++, Python, Java, Go, GCP, TensorFlow, Spanner',
                'employee_count': '180,000+ globally',
                'funding_stage': 'Public (NASDAQ: GOOGL)',
                'open_positions': 6,
                'internship_opportunities': 3,
                'jobs': [
                    {
                        'title': 'Software Engineer - University Graduate',
                        'job_type': 'Full-Time',
                        'work_mode': 'Hybrid',
                        'location': 'Bengaluru, Karnataka',
                        'salary': '22 - 35 LPA + Equity',
                        'minimum_cgpa': 8.0,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': '0 - 1 Years / Fresh Graduate',
                        'qualifications': 'B.Tech/M.Tech/Dual Degree in Computer Science or related STEM disciplines. World-class problem solving and analytical abilities.',
                        'description': 'Develop scalable backend solutions, optimize algorithms for Google Cloud infrastructure, and build resilient services serving billions of queries.',
                        'skills': ['Python', 'C++', 'Java', 'SQL', 'DSA', 'System Design'],
                        'days_deadline': 40,
                    },
                    {
                        'title': 'Associate Cloud Engineer - GCP',
                        'job_type': 'Full-Time',
                        'work_mode': 'Hybrid',
                        'location': 'Hyderabad, Telangana',
                        'salary': '18 - 28 LPA',
                        'minimum_cgpa': 7.5,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': 'Fresher / Entry-Level',
                        'qualifications': 'B.Tech CS/IT/ECE. Knowledge of containerization (Kubernetes), distributed databases, and Python scripting.',
                        'description': 'Design cloud migration frameworks and assist tier-1 enterprises in optimizing Google Cloud platform workloads.',
                        'skills': ['GCP', 'Kubernetes', 'Docker', 'Python', 'DevOps'],
                        'days_deadline': 50,
                    }
                ]
            },
            {
                'name': 'Microsoft',
                'company_type': 'Enterprise',
                'industry': 'Operating Systems, Cloud & Enterprise AI',
                'tagline': "Empowering every person and organization on the planet to achieve more",
                'description': 'Microsoft India Development Center (IDC) is one of Microsoft’s largest R&D centers outside Redmond. Teams create mission-critical software for Azure, Copilot, Windows, Office 365, and AI models.',
                'website': 'https://careers.microsoft.com',
                'logo_url': '/static/images/company_logos/microsoft.svg',
                'headquarters': 'Redmond, Washington, USA',
                'locations': 'Hyderabad, Bengaluru, Noida (Hybrid)',
                'tech_stack': 'C#, C++, Python, Azure, TypeScript, PyTorch',
                'employee_count': '220,000+ globally (20,000+ in India)',
                'funding_stage': 'Public (NASDAQ: MSFT)',
                'open_positions': 7,
                'internship_opportunities': 4,
                'jobs': [
                    {
                        'title': 'Software Engineer - Azure Core Platform',
                        'job_type': 'Full-Time',
                        'work_mode': 'Hybrid',
                        'location': 'Hyderabad, Telangana',
                        'salary': '18 - 30 LPA + Bonus',
                        'minimum_cgpa': 7.5,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': '0 - 2 Years',
                        'qualifications': 'B.Tech/M.Tech in CSE or allied streams. Excellent algorithmic foundations and systems programming.',
                        'description': 'Engineer high-throughput cloud infrastructure services for Microsoft Azure. Optimize multi-tenant virtual machines, distributed storage, and AI accelerators.',
                        'skills': ['C++', 'C#', 'Python', 'Azure', 'SQL', 'DSA'],
                        'days_deadline': 35,
                    },
                    {
                        'title': 'Data & Applied Scientist',
                        'job_type': 'Full-Time',
                        'work_mode': 'Remote',
                        'location': 'Bengaluru / Remote',
                        'salary': '20 - 32 LPA',
                        'minimum_cgpa': 8.0,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': 'Fresher to 2 Years',
                        'qualifications': 'Degree in Computer Science, Data Science, or Mathematics. Hands-on experience with ML frameworks and statistics.',
                        'description': 'Formulate and apply state-of-the-art NLP and GenAI models within Microsoft 365 Copilot products.',
                        'skills': ['Python', 'Machine Learning', 'Data Science', 'PyTorch', 'SQL', 'AI'],
                        'days_deadline': 55,
                    }
                ]
            },
            {
                'name': 'TCS',
                'company_type': 'Enterprise',
                'industry': 'IT Services, Digital Transformation & Consulting',
                'tagline': "Building on belief to engineer progressive digital futures for global enterprises",
                'description': 'Tata Consultancy Services (TCS) is India’s most valuable IT services multinational, operating across 50+ countries. TCS Digital and Prime hiring streams offer high-compensation roles to top engineering talent.',
                'website': 'https://www.tcs.com/careers',
                'logo_url': '/static/images/company_logos/tcs.svg',
                'headquarters': 'Mumbai, Maharashtra, India',
                'locations': 'Bhubaneswar, Pune, Chennai, Bengaluru, Kolkata',
                'tech_stack': 'Java, Python, Spring Boot, React, SQL, Cloud, Docker',
                'employee_count': '600,000+ employees',
                'funding_stage': 'Tata Group / Public (NSE: TCS)',
                'open_positions': 12,
                'internship_opportunities': 5,
                'jobs': [
                    {
                        'title': 'TCS Digital Engineer - Full Stack & Cloud',
                        'job_type': 'Full-Time',
                        'work_mode': 'Onsite',
                        'location': 'Bhubaneswar, Odisha',
                        'salary': '7.5 - 11.5 LPA',
                        'minimum_cgpa': 6.5,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': 'Fresher (2025/2026 Batch)',
                        'qualifications': 'B.Tech/B.E (All Branches) / MCA. Strong performance in TCS NQT or campus digital assessment.',
                        'description': 'Join high-priority enterprise modernization engagements building enterprise web solutions, cloud migrations, and real-time data pipelines.',
                        'skills': ['Java', 'Python', 'SQL', 'Spring Boot', 'React', 'AWS'],
                        'days_deadline': 60,
                    },
                    {
                        'title': 'TCS Prime Software Developer',
                        'job_type': 'Full-Time',
                        'work_mode': 'Hybrid',
                        'location': 'Pune, Maharashtra',
                        'salary': '9.0 - 14.0 LPA',
                        'minimum_cgpa': 7.0,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': 'Fresher / Entry-Level',
                        'qualifications': 'B.Tech in CS/IT/ECE. Expertise in algorithm optimization, microservices, and modern frameworks.',
                        'description': 'Work in TCS Advanced Technology Labs delivering next-generation AI and edge computing solutions.',
                        'skills': ['Python', 'Java', 'DSA', 'Docker', 'Git', 'REST API'],
                        'days_deadline': 45,
                    }
                ]
            },
            {
                'name': 'Infosys',
                'company_type': 'Enterprise',
                'industry': 'Next-Gen IT Consulting & Digital Services',
                'tagline': "Navigate your next with AI-first digital services and enterprise engineering",
                'description': 'Infosys is a global leader in next-generation digital services and consulting. With flagship engineering tracks like Specialist Programmer (SP) and Digital Specialist Engineer (DSE), Infosys recruits top coders for high-impact roles.',
                'website': 'https://www.infosys.com/careers',
                'logo_url': '/static/images/company_logos/infosys.svg',
                'headquarters': 'Bengaluru, Karnataka, India',
                'locations': 'Bhubaneswar, Bengaluru, Hyderabad, Pune, Mysuru',
                'tech_stack': 'Java, Python, Angular, React, Spring Boot, MySQL, Azure',
                'employee_count': '315,000+ employees',
                'funding_stage': 'Public (NSE: INFY)',
                'open_positions': 10,
                'internship_opportunities': 4,
                'jobs': [
                    {
                        'title': 'Specialist Programmer (SP)',
                        'job_type': 'Full-Time',
                        'work_mode': 'Hybrid',
                        'location': 'Bengaluru, Karnataka',
                        'salary': '9.5 - 15.0 LPA',
                        'minimum_cgpa': 7.0,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': 'Fresher / 0-1 Years',
                        'qualifications': 'B.Tech/M.Tech in CS/IT. Exceptional coding proficiency demonstrated in HackWithInfy or InfyTQ.',
                        'description': 'High-performance engineering role focusing on full-stack development, cloud architecture, and distributed microservices for Fortune 500 clients.',
                        'skills': ['Python', 'Java', 'SQL', 'React', 'Spring Boot', 'DSA'],
                        'days_deadline': 50,
                    }
                ]
            },
            {
                'name': 'Accenture',
                'company_type': 'Enterprise',
                'industry': 'Strategy, Consulting & Cloud Engineering',
                'tagline': "Let there be change: delivering on the promise of technology and human ingenuity",
                'description': 'Accenture is a Fortune Global 500 company providing consulting and technology services. Its Advanced Technology Centers in India (ATCI) drive large-scale cloud transformations and enterprise software engineering.',
                'website': 'https://www.accenture.com/in-en/careers',
                'logo_url': '/static/images/company_logos/accenture.svg',
                'headquarters': 'Dublin, Ireland',
                'locations': 'Bengaluru, Hyderabad, Pune, Mumbai, Gurugram',
                'tech_stack': 'Java, Python, SQL, Cloud, SAP, Testing, Spring Boot',
                'employee_count': '730,000+ globally',
                'funding_stage': 'Public (NYSE: ACN)',
                'open_positions': 9,
                'internship_opportunities': 3,
                'jobs': [
                    {
                        'title': 'Advanced Application Engineering Analyst',
                        'job_type': 'Full-Time',
                        'work_mode': 'Hybrid',
                        'location': 'Bengaluru, Karnataka',
                        'salary': '6.5 - 10.5 LPA',
                        'minimum_cgpa': 6.5,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': '0 - 1 Years / Fresher',
                        'qualifications': 'B.E / B.Tech / MCA. Understanding of cloud environments, SDLC, and testing frameworks.',
                        'description': 'Design, code, and test robust enterprise applications. Integrate cloud APIs, automate test suites, and support client production rollouts.',
                        'skills': ['Java', 'Python', 'SQL', 'Cloud', 'SAP', 'Testing'],
                        'days_deadline': 45,
                    }
                ]
            },
            {
                'name': 'Adobe',
                'company_type': 'Enterprise',
                'industry': 'Creative Cloud, Digital Media & Document Software',
                'tagline': "Changing the world through digital experiences and creative intelligence",
                'description': 'Adobe is the global leader in digital media and digital marketing solutions. Adobe India is a major R&D hub for Photoshop, Illustrator, Premiere Pro, Acrobat, and Adobe Firefly generative AI.',
                'website': 'https://www.adobe.com/careers.html',
                'logo_url': '/static/images/company_logos/adobe.svg',
                'headquarters': 'San Jose, California, USA',
                'locations': 'Noida & Bengaluru',
                'tech_stack': 'C++, Java, Python, WebAssembly, React, Machine Learning',
                'employee_count': '30,000+ globally',
                'funding_stage': 'Public (NASDAQ: ADBE)',
                'open_positions': 5,
                'internship_opportunities': 3,
                'jobs': [
                    {
                        'title': 'Member of Technical Staff - Creative Cloud',
                        'job_type': 'Full-Time',
                        'work_mode': 'Hybrid',
                        'location': 'Noida, Uttar Pradesh',
                        'salary': '18 - 28 LPA',
                        'minimum_cgpa': 7.5,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': '0 - 2 Years',
                        'qualifications': 'B.Tech/M.Tech in CS/IT. Strong C++ fundamentals, graphic rendering pipelines, and memory optimization.',
                        'description': 'Build high-performance graphics engine features, canvas rendering, and generative AI integrations within Adobe creative tools.',
                        'skills': ['C++', 'Python', 'DSA', 'Machine Learning', 'Git'],
                        'days_deadline': 40,
                    }
                ]
            },
            {
                'name': 'Deloitte',
                'company_type': 'Enterprise',
                'industry': 'Audit, Consulting, Risk Advisory & Cloud Tech',
                'tagline': "Making an impact that matters with cutting-edge business and tech advisory",
                'description': 'Deloitte USI (Deloitte Touche Tohmatsu) delivers strategy, cloud advisory, cybersecurity, and enterprise software engineering to Fortune 500 corporations worldwide.',
                'website': 'https://www2.deloitte.com/ui/en/careers.html',
                'logo_url': '/static/images/company_logos/deloitte.svg',
                'headquarters': 'London, UK / New York, USA',
                'locations': 'Hyderabad, Bengaluru, Mumbai, Gurugram',
                'tech_stack': 'Python, SQL, Power BI, Tableau, AWS, Azure, Data Analytics',
                'employee_count': '450,000+ globally',
                'funding_stage': 'Big Four Partnership',
                'open_positions': 6,
                'internship_opportunities': 2,
                'jobs': [
                    {
                        'title': 'Business Technology Analyst - Data & Analytics',
                        'job_type': 'Full-Time',
                        'work_mode': 'Hybrid',
                        'location': 'Hyderabad, Telangana',
                        'salary': '8.5 - 12.5 LPA',
                        'minimum_cgpa': 7.0,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': 'Fresher to 1 Year',
                        'qualifications': 'B.Tech / MCA with strong SQL proficiency, business intelligence, and storytelling with data.',
                        'description': 'Transform massive enterprise data sets into executive dashboards. Build automated ETL pipelines and deliver data analytics insights.',
                        'skills': ['SQL', 'Python', 'Data Analytics', 'Power BI', 'Tableau', 'Azure'],
                        'days_deadline': 35,
                    }
                ]
            },
            {
                'name': 'NVIDIA',
                'company_type': 'Enterprise',
                'industry': 'AI Supercomputing, GPU Architecture & Accelerated Computing',
                'tagline': "Pioneering GPU computing and generative AI infrastructure across the world",
                'description': 'NVIDIA is the pioneer of GPU-accelerated computing. NVIDIA India engineering centers in Bengaluru and Pune design cutting-edge hardware, CUDA software, AI supercomputers, and autonomous driving stacks.',
                'website': 'https://www.nvidia.com/en-in/about-nvidia/careers/',
                'logo_url': '/static/images/company_logos/nvidia.svg',
                'headquarters': 'Santa Clara, California, USA',
                'locations': 'Bengaluru & Pune',
                'tech_stack': 'C++, Python, CUDA, PyTorch, Linux, Deep Learning, Docker',
                'employee_count': '30,000+ globally',
                'funding_stage': 'Public (NASDAQ: NVDA)',
                'open_positions': 5,
                'internship_opportunities': 2,
                'jobs': [
                    {
                        'title': 'System Software Engineer - Deep Learning & CUDA',
                        'job_type': 'Full-Time',
                        'work_mode': 'Hybrid',
                        'location': 'Bengaluru, Karnataka',
                        'salary': '24 - 38 LPA + RSUs',
                        'minimum_cgpa': 8.0,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': '0 - 2 Years',
                        'qualifications': 'B.Tech/M.Tech in CS/ECE with expertise in low-level systems, CUDA programming, and GPU architecture.',
                        'description': 'Develop accelerated GPU software primitives for LLM training and real-time AI inference at massive scale.',
                        'skills': ['C++', 'Python', 'Machine Learning', 'Deep Learning', 'PyTorch', 'Linux'],
                        'days_deadline': 30,
                    }
                ]
            },
            {
                'name': 'JPMorgan Chase',
                'company_type': 'Enterprise',
                'industry': 'Investment Banking, Global Markets & FinTech',
                'tagline': "Pioneering financial solutions and ultra-resilient trading technology",
                'description': 'JPMorgan Chase is one of the world’s oldest and most prestigious financial institutions. Its Global Technology centers in India engineer low-latency algorithmic trading systems, cybersecurity, and blockchain frameworks.',
                'website': 'https://careers.jpmorgan.com',
                'logo_url': '/static/images/company_logos/jpmorgan.svg',
                'headquarters': 'New York City, New York, USA',
                'locations': 'Bengaluru, Mumbai, Hyderabad',
                'tech_stack': 'Java, Python, Spring Boot, React, SQL, Cloud, Kafka',
                'employee_count': '300,000+ globally',
                'funding_stage': 'Public (NYSE: JPM)',
                'open_positions': 6,
                'internship_opportunities': 3,
                'jobs': [
                    {
                        'title': 'Software Engineer - Global Technology',
                        'job_type': 'Full-Time',
                        'work_mode': 'Hybrid',
                        'location': 'Bengaluru, Karnataka',
                        'salary': '14 - 22 LPA',
                        'minimum_cgpa': 7.5,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': '0 - 1 Years / Fresher',
                        'qualifications': 'B.Tech in CS/IT/ECE. Solid comprehension of concurrent programming, database design, and microservices.',
                        'description': 'Engineer high-reliability financial payment processing pipelines and trade order matching systems with zero-downtime tolerance.',
                        'skills': ['Java', 'Python', 'SQL', 'Spring Boot', 'AWS', 'DSA'],
                        'days_deadline': 45,
                    }
                ]
            },
            {
                'name': 'Goldman Sachs',
                'company_type': 'Enterprise',
                'industry': 'Global Investment Banking & High-Frequency Tech',
                'tagline': "Engineering real-time financial systems and algorithmic market making",
                'description': 'Goldman Sachs engineers solve ultra-complex technical challenges in distributed systems, quantitative finance, cybersecurity, and machine learning.',
                'website': 'https://www.goldmansachs.com/careers',
                'logo_url': '/static/images/company_logos/goldmansachs.svg',
                'headquarters': 'New York City, New York, USA',
                'locations': 'Bengaluru & Hyderabad',
                'tech_stack': 'Java, C++, Python, React, SQL, Kafka, Linux',
                'employee_count': '45,000+ globally',
                'funding_stage': 'Public (NYSE: GS)',
                'open_positions': 5,
                'internship_opportunities': 2,
                'jobs': [
                    {
                        'title': 'Engineering Analyst - Quantitative Systems',
                        'job_type': 'Full-Time',
                        'work_mode': 'Onsite',
                        'location': 'Bengaluru, Karnataka',
                        'salary': '20 - 32 LPA',
                        'minimum_cgpa': 8.0,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': 'Fresher to 1 Year',
                        'qualifications': 'B.Tech/M.Tech with mathematical aptitude, deep understanding of algorithms and low-latency programming.',
                        'description': 'Build algorithmic pricing engines, risk analytics tools, and real-time distributed streaming architectures.',
                        'skills': ['Java', 'C++', 'Python', 'SQL', 'DSA', 'Linux'],
                        'days_deadline': 40,
                    }
                ]
            },
            {
                'name': 'Walmart',
                'company_type': 'Enterprise',
                'industry': 'Retail Tech, Supply Chain Automation & E-Commerce',
                'tagline': "Saving people money so they can live better through retail technology",
                'description': 'Walmart Global Tech in Bengaluru and Chennai powers the retail technology for Walmart stores, Sam’s Club, and e-commerce platforms serving 250M+ customers weekly.',
                'website': 'https://careers.walmart.com',
                'logo_url': '/static/images/company_logos/walmart.svg',
                'headquarters': 'Bentonville, Arkansas, USA',
                'locations': 'Bengaluru & Chennai',
                'tech_stack': 'Java, Python, React, Kubernetes, Kafka, Cloud',
                'employee_count': '2,100,000+ globally',
                'funding_stage': 'Public (NYSE: WMT)',
                'open_positions': 5,
                'internship_opportunities': 2,
                'jobs': [
                    {
                        'title': 'Software Engineer - Supply Chain & Fulfillment',
                        'job_type': 'Full-Time',
                        'work_mode': 'Hybrid',
                        'location': 'Bengaluru, Karnataka',
                        'salary': '15 - 24 LPA',
                        'minimum_cgpa': 7.5,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': '0 - 2 Years',
                        'qualifications': 'B.Tech in Computer Science or related fields. Experience in object-oriented programming and microservices.',
                        'description': 'Optimize automated inventory distribution, predictive logistics algorithms, and store fulfillment platforms.',
                        'skills': ['Java', 'Python', 'SQL', 'Spring Boot', 'Kafka', 'Docker'],
                        'days_deadline': 45,
                    }
                ]
            },
            {
                'name': 'Flipkart',
                'company_type': 'Unicorn',
                'industry': 'E-Commerce, Logistics Tech & Digital Payments',
                'tagline': "India's homegrown e-commerce marketplace democratizing digital commerce",
                'description': 'Flipkart revolutionized Indian e-commerce with Cash-on-Delivery, Big Billion Days, and super-fast delivery networks. Flipkart engineering tackles massive concurrency, algorithmic search, and fraud prevention.',
                'website': 'https://www.flipkartcareers.com',
                'logo_url': '/static/images/company_logos/flipkart.svg',
                'headquarters': 'Bengaluru, Karnataka, India',
                'locations': 'Bengaluru, Karnataka',
                'tech_stack': 'Java, Python, Go, MySQL, Kafka, Redis, Docker',
                'employee_count': '30,000+ employees',
                'funding_stage': 'Walmart-backed / $38B Valuation',
                'open_positions': 6,
                'internship_opportunities': 3,
                'jobs': [
                    {
                        'title': 'Software Development Engineer - I (SDE 1)',
                        'job_type': 'Full-Time',
                        'work_mode': 'Hybrid',
                        'location': 'Bengaluru, Karnataka',
                        'salary': '18 - 28 LPA',
                        'minimum_cgpa': 7.5,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': '0 - 1 Years',
                        'qualifications': 'B.Tech CS/IT. Strong problem solving, data structures, and multi-threaded system architecture.',
                        'description': 'Build high-scale checkout flows, real-time catalog search indexing, and promotional pricing engines handling 100k+ requests/sec.',
                        'skills': ['Java', 'Python', 'SQL', 'DSA', 'Redis', 'Kafka'],
                        'days_deadline': 40,
                    }
                ]
            },
            {
                'name': 'Oracle',
                'company_type': 'Enterprise',
                'industry': 'Database Technologies & Oracle Cloud Infrastructure (OCI)',
                'tagline': "Creating the future of cloud databases, autonomous systems, and AI applications",
                'description': 'Oracle is the benchmark in relational and autonomous database technologies. Oracle Cloud Infrastructure (OCI) in Bengaluru and Hyderabad builds next-generation cloud infrastructure, bare-metal compute, and enterprise SaaS.',
                'website': 'https://www.oracle.com/corporate/careers/',
                'logo_url': '/static/images/company_logos/oracle.svg',
                'headquarters': 'Austin, Texas, USA',
                'locations': 'Bengaluru, Hyderabad, Pune',
                'tech_stack': 'Java, C++, Python, SQL, Cloud, Linux, Docker',
                'employee_count': '160,000+ globally',
                'funding_stage': 'Public (NYSE: ORCL)',
                'open_positions': 6,
                'internship_opportunities': 2,
                'jobs': [
                    {
                        'title': 'Software Engineer - Oracle Cloud Infrastructure (OCI)',
                        'job_type': 'Full-Time',
                        'work_mode': 'Hybrid',
                        'location': 'Bengaluru, Karnataka',
                        'salary': '16 - 25 LPA',
                        'minimum_cgpa': 7.0,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': 'Fresher to 2 Years',
                        'qualifications': 'B.Tech/M.Tech in CSE or related domains. Deep knowledge of OS internals, networking, and distributed storage.',
                        'description': 'Develop scalable cloud control planes, virtual network overlays, and autonomous database clustering components.',
                        'skills': ['Java', 'C++', 'SQL', 'Cloud', 'Linux', 'DSA'],
                        'days_deadline': 50,
                    }
                ]
            },
            {
                'name': 'Salesforce',
                'company_type': 'Enterprise',
                'industry': 'CRM, Cloud Enterprise & Agentforce AI',
                'tagline': "Bringing companies and customers together through intelligent cloud workflows",
                'description': 'Salesforce is the worlds #1 CRM platform, pioneering multi-tenant enterprise cloud applications. Salesforce India engineers develop core capabilities across Service Cloud, Marketing Cloud, and Agentforce autonomous AI.',
                'website': 'https://www.salesforce.com/company/careers/',
                'logo_url': '/static/images/company_logos/salesforce.svg',
                'headquarters': 'San Francisco, California, USA',
                'locations': 'Hyderabad & Bengaluru',
                'tech_stack': 'Java, Python, JavaScript, React, Cloud, SQL, AI',
                'employee_count': '75,000+ globally',
                'funding_stage': 'Public (NYSE: CRM)',
                'open_positions': 5,
                'internship_opportunities': 2,
                'jobs': [
                    {
                        'title': 'Associate Member of Technical Staff (AMTS)',
                        'job_type': 'Full-Time',
                        'work_mode': 'Hybrid',
                        'location': 'Hyderabad, Telangana',
                        'salary': '16 - 24 LPA',
                        'minimum_cgpa': 7.5,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': '0 - 1 Years',
                        'qualifications': 'B.Tech/B.E in CS/IT. Strong grasp of OOP, modern web frameworks, and cloud API integrations.',
                        'description': 'Engineer multi-tenant cloud applications, write unit and end-to-end integration tests, and collaborate with global development teams.',
                        'skills': ['Java', 'JavaScript', 'React', 'Cloud', 'SQL', 'REST API'],
                        'days_deadline': 45,
                    }
                ]
            },
            {
                'name': 'Cisco',
                'company_type': 'Enterprise',
                'industry': 'Networking Hardware, Cybersecurity & Cloud Infrastructure',
                'tagline': "Connecting everyone and securing everything through advanced network intelligence",
                'description': 'Cisco powers the backbone of the global internet. Cisco India engineering center in Bengaluru is its largest outside California, innovating across routers, switches, cybersecurity, and Webex.',
                'website': 'https://www.cisco.com/c/en/us/about/careers.html',
                'logo_url': '/static/images/company_logos/cisco.svg',
                'headquarters': 'San Jose, California, USA',
                'locations': 'Bengaluru, Karnataka',
                'tech_stack': 'C, C++, Python, Linux, Networking, Docker, Cloud',
                'employee_count': '85,000+ globally',
                'funding_stage': 'Public (NASDAQ: CSCO)',
                'open_positions': 5,
                'internship_opportunities': 2,
                'jobs': [
                    {
                        'title': 'Software Engineer - Network Operating Systems',
                        'job_type': 'Full-Time',
                        'work_mode': 'Hybrid',
                        'location': 'Bengaluru, Karnataka',
                        'salary': '14 - 22 LPA',
                        'minimum_cgpa': 7.0,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': 'Fresher to 1 Year',
                        'qualifications': 'B.Tech in CS/ECE/IT. Proficient in C/C++, Linux kernel/system programming, and TCP/IP stack.',
                        'description': 'Develop robust network protocol daemons (BGP, OSPF, EVPN) and hardware-abstracted switching software for Cisco Nexus and Catalyst.',
                        'skills': ['C', 'C++', 'Python', 'Linux', 'DSA', 'DevOps'],
                        'days_deadline': 40,
                    }
                ]
            },
            {
                'name': 'Intel',
                'company_type': 'Enterprise',
                'industry': 'Semiconductors, Microprocessors & AI Accelerators',
                'tagline': "Creating world-changing technology that enriches the life of every person",
                'description': 'Intel is a technology leader shaping the data-centric future with x86 architecture, FPGA solutions, and Gaudi AI accelerators. Intel India is a premier design center for microarchitectures and software optimization.',
                'website': 'https://www.intel.com/content/www/us/en/jobs/jobs-at-intel.html',
                'logo_url': '/static/images/company_logos/intel.svg',
                'headquarters': 'Santa Clara, California, USA',
                'locations': 'Bengaluru, Karnataka',
                'tech_stack': 'C, C++, Python, Linux, Embedded, DSA, Machine Learning',
                'employee_count': '125,000+ globally',
                'funding_stage': 'Public (NASDAQ: INTC)',
                'open_positions': 4,
                'internship_opportunities': 2,
                'jobs': [
                    {
                        'title': 'Software Engineer - AI Frameworks & Compilers',
                        'job_type': 'Full-Time',
                        'work_mode': 'Hybrid',
                        'location': 'Bengaluru, Karnataka',
                        'salary': '15 - 24 LPA',
                        'minimum_cgpa': 7.5,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': '0 - 2 Years',
                        'qualifications': 'B.Tech/M.Tech in CS/ECE. Proficiency in C/C++, compiler optimization (LLVM), and ML framework runtimes.',
                        'description': 'Accelerate PyTorch and TensorFlow inference models on Intel Core Ultra and Xeon processors with OpenVINO and oneAPI libraries.',
                        'skills': ['C++', 'Python', 'Machine Learning', 'Linux', 'DSA'],
                        'days_deadline': 45,
                    }
                ]
            },
            {
                'name': 'Wipro',
                'company_type': 'Enterprise',
                'industry': 'IT Services, AI Solutions & Cloud Transformation',
                'tagline': "Ambitions realized through innovation, cloud, and AI engineering",
                'description': 'Wipro is a prominent Indian technology services and consulting company delivering digital engineering, cybersecurity, and cloud migration services to global organizations.',
                'website': 'https://careers.wipro.com',
                'logo_url': '/static/images/company_logos/wipro.svg',
                'headquarters': 'Bengaluru, Karnataka, India',
                'locations': 'Bhubaneswar, Bengaluru, Hyderabad, Chennai, Pune',
                'tech_stack': 'Java, Python, SQL, Cloud, React, Testing, DevOps',
                'employee_count': '240,000+ employees',
                'funding_stage': 'Public (NSE: WIPRO)',
                'open_positions': 8,
                'internship_opportunities': 3,
                'jobs': [
                    {
                        'title': 'Project Engineer - Digital & Cloud Solutions',
                        'job_type': 'Full-Time',
                        'work_mode': 'Onsite',
                        'location': 'Bhubaneswar, Odisha',
                        'salary': '6.5 - 9.5 LPA',
                        'minimum_cgpa': 6.5,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': 'Fresher / Entry-Level',
                        'qualifications': 'B.Tech/B.E in any engineering branch. Basic understanding of programming and web architecture.',
                        'description': 'Design and maintain enterprise applications, write automated tests, and collaborate on agile delivery sprints.',
                        'skills': ['Java', 'Python', 'SQL', 'React', 'Cloud', 'Git'],
                        'days_deadline': 60,
                    }
                ]
            },
            {
                'name': 'Cognizant',
                'company_type': 'Enterprise',
                'industry': 'Digital Business Solutions & Enterprise IT',
                'tagline': "Engineering modern businesses to improve everyday life",
                'description': 'Cognizant helps clients modernize technology, reimagine processes and transform experiences. Its GenC Elevate and Pro tracks recruit talented developers for advanced technology roles.',
                'website': 'https://careers.cognizant.com',
                'logo_url': '/static/images/company_logos/cognizant.svg',
                'headquarters': 'Teaneck, New Jersey, USA',
                'locations': 'Chennai, Bengaluru, Hyderabad, Pune, Kolkata',
                'tech_stack': 'Java, Python, Spring Boot, React, SQL, Cloud, Testing',
                'employee_count': '340,000+ employees',
                'funding_stage': 'Public (NASDAQ: CTSH)',
                'open_positions': 7,
                'internship_opportunities': 3,
                'jobs': [
                    {
                        'title': 'Programmer Analyst Trainee - GenC Next',
                        'job_type': 'Full-Time',
                        'work_mode': 'Hybrid',
                        'location': 'Bengaluru, Karnataka',
                        'salary': '6.75 - 9.25 LPA',
                        'minimum_cgpa': 6.5,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': 'Fresher (2025/2026 Batch)',
                        'qualifications': 'B.Tech / MCA with solid analytical thinking, problem-solving, and foundation in OOP.',
                        'description': 'Develop backend microservices, write clean REST APIs, and deploy cloud-native solutions for healthcare and financial services clients.',
                        'skills': ['Java', 'Python', 'SQL', 'Spring Boot', 'Cloud', 'Testing'],
                        'days_deadline': 50,
                    }
                ]
            },
            {
                'name': 'Capgemini',
                'company_type': 'Enterprise',
                'industry': 'Consulting, Digital Transformation & Engineering',
                'tagline': "Get the future you want with technology and human innovation",
                'description': 'Capgemini is a global leader partnering with companies to transform and manage their business through technology. With deep cloud, data, and AI expertise, Capgemini India employs over 150,000 professionals.',
                'website': 'https://www.capgemini.com/in-en/careers/',
                'logo_url': '/static/images/company_logos/capgemini.svg',
                'headquarters': 'Paris, France',
                'locations': 'Bengaluru, Mumbai, Pune, Hyderabad, Chennai',
                'tech_stack': 'Java, Python, Cloud, SAP, Angular, SQL, Testing',
                'employee_count': '360,000+ globally',
                'funding_stage': 'Public (Euronext: CAP)',
                'open_positions': 7,
                'internship_opportunities': 2,
                'jobs': [
                    {
                        'title': 'Senior Analyst - Cloud & Custom Software Development',
                        'job_type': 'Full-Time',
                        'work_mode': 'Hybrid',
                        'location': 'Pune, Maharashtra',
                        'salary': '7.5 - 11.0 LPA',
                        'minimum_cgpa': 6.8,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': '0 - 2 Years',
                        'qualifications': 'B.Tech CS/IT/ECE. Understanding of CI/CD, Git, relational databases, and enterprise Java.',
                        'description': 'Develop full-stack enterprise applications, modernize legacy systems, and build automated deployments on AWS and Azure.',
                        'skills': ['Java', 'Python', 'SQL', 'Cloud', 'SAP', 'Testing'],
                        'days_deadline': 45,
                    }
                ]
            },
            {
                'name': 'HCLTech',
                'company_type': 'Enterprise',
                'industry': 'Supercharged Technology Services & Digital Engineering',
                'tagline': "Supercharging progress for enterprises through cutting-edge digital capabilities",
                'description': 'HCLTech is a global technology company home to 220,000+ people across 60 countries, delivering industry-leading capabilities centered around digital, engineering, cloud, and AI.',
                'website': 'https://www.hcltech.com/careers',
                'logo_url': '/static/images/company_logos/hcltech.svg',
                'headquarters': 'Noida, Uttar Pradesh, India',
                'locations': 'Noida, Bengaluru, Chennai, Hyderabad, Lucknow',
                'tech_stack': 'Java, Python, C++, SQL, Cloud, Testing, DevOps',
                'employee_count': '220,000+ employees',
                'funding_stage': 'Public (NSE: HCLTECH)',
                'open_positions': 6,
                'internship_opportunities': 2,
                'jobs': [
                    {
                        'title': 'Graduate Engineer Trainee - Software Development',
                        'job_type': 'Full-Time',
                        'work_mode': 'Onsite',
                        'location': 'Noida, Uttar Pradesh',
                        'salary': '6.0 - 9.0 LPA',
                        'minimum_cgpa': 6.5,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': 'Fresher',
                        'qualifications': 'B.Tech/B.E in Computer Science, IT, or related streams. Sound foundational coding skills.',
                        'description': 'Work in agile software development squads delivering telecom, healthcare, and financial engineering products.',
                        'skills': ['Java', 'Python', 'SQL', 'Cloud', 'Git', 'Testing'],
                        'days_deadline': 55,
                    }
                ]
            },
            {
                'name': 'Tech Mahindra',
                'company_type': 'Enterprise',
                'industry': 'Connected World Experiences, Telecom & AI Systems',
                'tagline': "Scale at speed with digital innovation and autonomous enterprise tech",
                'description': 'Tech Mahindra offers innovative customer-centric digital experiences. A $6.5B organization with 145,000+ professionals across 90 countries, it leads in 5G, telecommunication networks, and generative AI platforms.',
                'website': 'https://www.techmahindra.com/en-in/careers/',
                'logo_url': '/static/images/company_logos/techmahindra.svg',
                'headquarters': 'Pune, Maharashtra, India',
                'locations': 'Bhubaneswar, Pune, Hyderabad, Bengaluru, Chennai',
                'tech_stack': 'Python, Java, React, SQL, Cloud, Telecom, AI',
                'employee_count': '145,000+ employees',
                'funding_stage': 'Mahindra Group / Public (NSE: TECHM)',
                'open_positions': 6,
                'internship_opportunities': 2,
                'jobs': [
                    {
                        'title': 'Associate Software Engineer - 5G & Cloud Platforms',
                        'job_type': 'Full-Time',
                        'work_mode': 'Hybrid',
                        'location': 'Bhubaneswar, Odisha',
                        'salary': '5.5 - 8.5 LPA',
                        'minimum_cgpa': 6.5,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': 'Fresher to 1 Year',
                        'qualifications': 'B.Tech CS/IT/ECE. Solid understanding of programming languages, Linux, and database queries.',
                        'description': 'Build telecommunication billing and network orchestration microservices using Python, Java, and cloud platforms.',
                        'skills': ['Python', 'Java', 'SQL', 'Cloud', 'Linux', 'Git'],
                        'days_deadline': 60,
                    }
                ]
            },
            {
                'name': 'IBM',
                'company_type': 'Enterprise',
                'industry': 'Hybrid Cloud, Enterprise AI & Quantum Systems',
                'tagline': "Creating hybrid cloud and AI breakthroughs that transform business operations",
                'description': 'IBM is a global technology and consulting innovator. IBM India Software Labs (ISL) is a powerhouse of engineering building Red Hat OpenShift integrations, watsonx enterprise AI models, and hybrid cloud storage.',
                'website': 'https://www.ibm.com/careers',
                'logo_url': '/static/images/company_logos/ibm.svg',
                'headquarters': 'Armonk, New York, USA',
                'locations': 'Bengaluru, Hyderabad, Kochi, Pune',
                'tech_stack': 'Python, Java, Go, Kubernetes, Docker, watsonx, SQL',
                'employee_count': '280,000+ globally',
                'funding_stage': 'Public (NYSE: IBM)',
                'open_positions': 5,
                'internship_opportunities': 2,
                'jobs': [
                    {
                        'title': 'Software Developer - Hybrid Cloud & OpenShift',
                        'job_type': 'Full-Time',
                        'work_mode': 'Hybrid',
                        'location': 'Bengaluru, Karnataka',
                        'salary': '12 - 18 LPA',
                        'minimum_cgpa': 7.0,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': '0 - 2 Years',
                        'qualifications': 'B.Tech/M.Tech in Computer Science. Knowledge of containerization, Linux operating system, and Go/Java.',
                        'description': 'Develop cloud automation controllers, Kubernetes operators, and microservices powering enterprise hybrid cloud deployments.',
                        'skills': ['Python', 'Java', 'Docker', 'Kubernetes', 'Cloud', 'Git'],
                        'days_deadline': 45,
                    }
                ]
            },
            {
                'name': 'Atlassian',
                'company_type': 'Enterprise',
                'industry': 'Developer Tools, Collaboration & Agile Software',
                'tagline': "Unleashing the potential of every team with Jira, Confluence, and Bitbucket",
                'description': 'Atlassian builds products like Jira, Confluence, Bitbucket, and Trello used by millions of software engineers and teams worldwide. Its Bengaluru R&D center leads major product engineering.',
                'website': 'https://www.atlassian.com/company/careers',
                'logo_url': '/static/images/company_logos/atlassian.svg',
                'headquarters': 'Sydney, Australia',
                'locations': 'Bengaluru, Karnataka (Remote / Hybrid)',
                'tech_stack': 'Java, React, TypeScript, Python, AWS, PostgreSQL, Docker',
                'employee_count': '11,000+ globally',
                'funding_stage': 'Public (NASDAQ: TEAM)',
                'open_positions': 4,
                'internship_opportunities': 2,
                'jobs': [
                    {
                        'title': 'Software Engineer - Jira Cloud Platform',
                        'job_type': 'Full-Time',
                        'work_mode': 'Remote',
                        'location': 'Bengaluru / Remote',
                        'salary': '20 - 32 LPA + Equity',
                        'minimum_cgpa': 7.5,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': '0 - 2 Years',
                        'qualifications': 'B.Tech in Computer Science. Strong experience with Java or React/TypeScript, clean architecture, and API design.',
                        'description': 'Build highly interactive, resilient micro-frontends and backend services powering Jira workflows for millions of concurrent users.',
                        'skills': ['Java', 'React', 'TypeScript', 'SQL', 'AWS', 'DSA'],
                        'days_deadline': 40,
                    }
                ]
            },
            {
                'name': 'SAP',
                'company_type': 'Enterprise',
                'industry': 'Enterprise Resource Planning & Business AI',
                'tagline': "Helping the world run better and improving people’s lives through enterprise ERP",
                'description': 'SAP is the world leader in enterprise application software. SAP Labs India in Bengaluru is SAP’s second-largest R&D center, creating SAP S/4HANA, Business Technology Platform, and Business AI solutions.',
                'website': 'https://jobs.sap.com',
                'logo_url': '/static/images/company_logos/sap.svg',
                'headquarters': 'Walldorf, Germany',
                'locations': 'Bengaluru & Gurugram',
                'tech_stack': 'Java, Python, SAP, HANA, JavaScript, Cloud, Docker',
                'employee_count': '105,000+ globally',
                'funding_stage': 'Public (NYSE: SAP)',
                'open_positions': 5,
                'internship_opportunities': 2,
                'jobs': [
                    {
                        'title': 'Developer Associate - SAP Business Technology Platform',
                        'job_type': 'Full-Time',
                        'work_mode': 'Hybrid',
                        'location': 'Bengaluru, Karnataka',
                        'salary': '12 - 18 LPA',
                        'minimum_cgpa': 7.0,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': '0 - 1 Years',
                        'qualifications': 'B.Tech/M.Tech in CS/IT. Strong analytical thinking and hands-on programming with Java, Python, or JavaScript.',
                        'description': 'Design cloud services on SAP BTP, integrate machine learning services into S/4HANA enterprise workflows, and deploy microservices.',
                        'skills': ['Java', 'Python', 'SQL', 'SAP', 'Cloud', 'REST API'],
                        'days_deadline': 45,
                    }
                ]
            },
            {
                'name': 'Morgan Stanley',
                'company_type': 'Enterprise',
                'industry': 'Global Financial Advisory, Wealth Management & FinTech',
                'tagline': "Empowering markets, clients, and innovators with high-impact technology",
                'description': 'Morgan Stanley is a global investment bank and wealth management firm. Its technology division in Mumbai and Bengaluru develops trading platforms, algorithmic execution engines, and risk models.',
                'website': 'https://www.morganstanley.com/people-opportunities/careers',
                'logo_url': '/static/images/company_logos/morganstanley.svg',
                'headquarters': 'New York City, New York, USA',
                'locations': 'Mumbai & Bengaluru',
                'tech_stack': 'Java, C++, Python, SQL, Linux, Spring Boot, React',
                'employee_count': '80,000+ globally',
                'funding_stage': 'Public (NYSE: MS)',
                'open_positions': 4,
                'internship_opportunities': 2,
                'jobs': [
                    {
                        'title': 'Technology Analyst - Institutional Securities Tech',
                        'job_type': 'Full-Time',
                        'work_mode': 'Hybrid',
                        'location': 'Mumbai, Maharashtra',
                        'salary': '15 - 24 LPA',
                        'minimum_cgpa': 7.5,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': 'Fresher to 1 Year',
                        'qualifications': 'B.Tech/M.Tech in CS/IT. Excellent foundations in data structures, algorithms, and multithreading.',
                        'description': 'Build low-latency order routing systems, algorithmic risk calculators, and real-time trade monitoring dashboards.',
                        'skills': ['Java', 'C++', 'Python', 'SQL', 'DSA', 'Linux'],
                        'days_deadline': 40,
                    }
                ]
            },
            {
                'name': 'PwC',
                'company_type': 'Enterprise',
                'industry': 'Assurance, Advisory & Enterprise Cloud Engineering',
                'tagline': "Building trust in society and solving important problems through tech innovation",
                'description': 'PwC (PricewaterhouseCoopers) is one of the Big Four professional services networks, providing digital transformation, cloud architecture, cybersecurity, and enterprise software engineering.',
                'website': 'https://www.pwc.in/careers.html',
                'logo_url': '/static/images/company_logos/pwc.svg',
                'headquarters': 'London, UK',
                'locations': 'Kolkata, Bengaluru, Hyderabad, Mumbai, Gurugram',
                'tech_stack': 'Python, SQL, Azure, AWS, Power BI, Data Analytics, Testing',
                'employee_count': '360,000+ globally',
                'funding_stage': 'Big Four Partnership',
                'open_positions': 5,
                'internship_opportunities': 2,
                'jobs': [
                    {
                        'title': 'Associate - Cloud & Technology Consulting',
                        'job_type': 'Full-Time',
                        'work_mode': 'Hybrid',
                        'location': 'Kolkata, West Bengal',
                        'salary': '7.0 - 10.5 LPA',
                        'minimum_cgpa': 6.5,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': 'Fresher',
                        'qualifications': 'B.Tech/MCA with aptitude in databases, cloud services, and software engineering.',
                        'description': 'Assist global clients in architecting cloud migrations, automating financial workflows, and deploying data pipelines.',
                        'skills': ['Python', 'SQL', 'Cloud', 'Data Analytics', 'Power BI', 'Git'],
                        'days_deadline': 45,
                    }
                ]
            },
            {
                'name': 'EY',
                'company_type': 'Enterprise',
                'industry': 'Strategy, Consulting & Emerging Tech Advisory',
                'tagline': "Building a better working world with AI, automation, and transformative technology",
                'description': 'Ernst & Young (EY) Global Delivery Services (GDS) in India powers technology innovation across artificial intelligence, cybersecurity, cloud architecture, and data engineering.',
                'website': 'https://www.ey.com/en_in/careers',
                'logo_url': '/static/images/company_logos/ey.svg',
                'headquarters': 'London, UK',
                'locations': 'Bengaluru, Hyderabad, Kochi, Kolkata, Gurugram',
                'tech_stack': 'Python, SQL, Azure, Power BI, AI, Data Science, Testing',
                'employee_count': '395,000+ globally',
                'funding_stage': 'Big Four Partnership',
                'open_positions': 6,
                'internship_opportunities': 2,
                'jobs': [
                    {
                        'title': 'Associate Consultant - Data Science & AI',
                        'job_type': 'Full-Time',
                        'work_mode': 'Hybrid',
                        'location': 'Bengaluru, Karnataka',
                        'salary': '8.0 - 12.0 LPA',
                        'minimum_cgpa': 7.0,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': '0 - 1 Years',
                        'qualifications': 'B.Tech in CS/IT/Data Science. Experience with Python, statistical modeling, and machine learning libraries.',
                        'description': 'Construct predictive models, automate enterprise document parsing using LLMs, and build data visualization solutions.',
                        'skills': ['Python', 'SQL', 'Data Science', 'Machine Learning', 'Power BI', 'AI'],
                        'days_deadline': 50,
                    }
                ]
            },
            {
                'name': 'KPMG',
                'company_type': 'Enterprise',
                'industry': 'Audit, Tax & Digital Engineering Advisory',
                'tagline': "Inspiring confidence and empowering change through digital technologies",
                'description': 'KPMG is a global network of professional services firms providing digital transformation, cyber strategy, enterprise ERP, and cloud engineering across 140+ countries.',
                'website': 'https://kpmg.com/in/en/home/careers.html',
                'logo_url': '/static/images/company_logos/kpmg.svg',
                'headquarters': 'Amstelveen, Netherlands',
                'locations': 'Bengaluru, Mumbai, Gurugram, Hyderabad',
                'tech_stack': 'Python, SQL, Cloud, Power BI, DevOps, Testing, Java',
                'employee_count': '270,000+ globally',
                'funding_stage': 'Big Four Partnership',
                'open_positions': 4,
                'internship_opportunities': 2,
                'jobs': [
                    {
                        'title': 'Analyst - Cyber Defense & Cloud Infrastructure',
                        'job_type': 'Full-Time',
                        'work_mode': 'Hybrid',
                        'location': 'Bengaluru, Karnataka',
                        'salary': '7.5 - 11.0 LPA',
                        'minimum_cgpa': 6.8,
                        'graduation_year': 2025,
                        'experience_required': 0.0,
                        'experience_text': 'Fresher to 1 Year',
                        'qualifications': 'B.Tech in CS/IT/Cybersecurity. Understanding of network security, cloud governance, and vulnerability testing.',
                        'description': 'Assess cloud infrastructure postures, conduct security code reviews, and automate compliance audits.',
                        'skills': ['Python', 'SQL', 'Cloud', 'DevOps', 'Testing', 'Git'],
                        'days_deadline': 40,
                    }
                ]
            }
        ]

        now = timezone.now()
        total_companies_created = 0
        total_jobs_created = 0

        for comp_data in enterprises:
            jobs_list = comp_data.pop('jobs', [])
            company, created = Company.objects.update_or_create(
                name=comp_data['name'],
                defaults=comp_data
            )
            if created:
                total_companies_created += 1

            for j_data in jobs_list:
                skill_names = j_data.pop('skills', [])
                days = j_data.pop('days_deadline', 45)
                deadline = now + datetime.timedelta(days=days)

                job, j_created = Job.objects.update_or_create(
                    company=company,
                    title=j_data['title'],
                    defaults={
                        'description': j_data['description'],
                        'location': j_data['location'],
                        'job_type': j_data['job_type'],
                        'work_mode': j_data['work_mode'],
                        'salary': j_data['salary'],
                        'minimum_cgpa': j_data['minimum_cgpa'],
                        'graduation_year': j_data['graduation_year'],
                        'experience_required': j_data['experience_required'],
                        'experience_text': j_data.get('experience_text', ''),
                        'qualifications': j_data.get('qualifications', ''),
                        'application_deadline': deadline,
                        'is_verified': True,
                        'is_active': True,
                    }
                )
                if j_created:
                    total_jobs_created += 1

                # Attach skills
                for s_name in skill_names:
                    if s_name in skill_objs:
                        job.required_skills.add(skill_objs[s_name])

        self.stdout.write(self.style.SUCCESS(
            f'Successfully seeded {len(enterprises)} enterprise companies with verified jobs and official logos!'
        ))
